### PR TITLE
missing character added

### PR DESCRIPTION
**Pull request by stakemepro**
This character will allow you to send the command in full

### CODE REVIEW

**Review by amimart — APPROVED** [review]
Nice catch thank you 😉

**Review by bdeneux — CHANGES_REQUESTED** [review]
Thank you for contribution ! ;) 
Since this PR is duplicated by https://github.com/okp4/networks/pull/112, already merged, is because the README is generated by the template `README.md.gtpl` https://github.com/okp4/networks/blob/main/chains/nemeton-1/README.md.gtpl#L38 could you please update also the [template](https://github.com/okp4/networks/blob/main/chains/nemeton-1/README.md.gtpl#L38), otherwise this mistake will reappears always :) 
Thanks

**Comment by stakemepro** [comment]
That's right, I replaced it. Thanks

**Review by bdeneux — APPROVED** [review]
Nice thank you 🙂

**Review by ccamel — APPROVED** [review]
Great. Thanks. 👍

**Pull request merged**
