### PR TITLE
🔥 Forge the `nemeton` genesis

### PR DESCRIPTION
**Pull request by ccamel**
This PR aims to forge the genesis file named `nemeton` for the the first main OKP4 testnet.

**Todo:**

- [x] Implement state for modules (wasm, logic)
- [x] Implement the tokenomics stated in the [OKP4 Whitepaper](https://docs.okp4.network/docs/whitepaper/tokenomics)
   - [x] Allowed validators limit
   - [x] Token emission (staking rewards)
   - [x] Token allocations (with cliff & vesting)

### CODE REVIEW

**Comment by ccamel** [comment]
image

**Comment by amimart** [comment]
A precision about the mint parameters: The `mint` module populate the new inflation rate every blocks against the total supply containing minted coins, the inflation model written in the whitepaper is different, the inflation rate change only every.

The `mint` module shall be re-implemented but for now, by setting the initial inflation rate to [7,5% instead of 15%](https://github.com/okp4/okp4d/pull/179) will lead to the same number of minted coins but not linearly.

**Review by amimart — APPROVED** [review]

**Review by bdeneux — APPROVED** [review]
🚀

**Comment by ccamel** [comment]
Good to me! :rocket:

**Review by ad2ien — APPROVED** [review]

**Pull request merged**
